version: "3"

services:
  mysql:
    container_name: compx322assn2_mysql
    tty: true
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=zs284
      - MYSQL_USER=zs284
      - MYSQL_PASSWORD=my525041sql
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
    networks:
      - compx322
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
      - "sql:/var/lib/mysql"

  php:
    container_name: compx322assn2_php
    build: ./
    user: "${UID}:${GID}"
    environment:
      - HOST=mysql
    tty: true
    networks:
      - compx322
    volumes:
      - "~/.ssh:/root/.ssh:ro"
      - "..:/workspaces"

  nginx:
    container_name: compx322assn2_nginx
    image: nginx:stable-alpine
    tty: true
    ports:
      - "322:80"
    depends_on:
      - php
    networks:
      - compx322
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
      - "../html:/workspaces/html"

networks:
  compx322:
    name: compx322
    driver: bridge

volumes:
  sql:
    driver: local
