FROM mysql:latest

ENV MYSQL_DATABASE=zs284
ENV MYSQL_USER=zs284
ENV MYSQL_PASSWORD=my525041sql
ENV MYSQL_ALLOW_EMPTY_PASSWORD=1
ENV SERVICE_TAGS=dev
ENV SERVICE_NAME=mysql

ADD ./sql/* /docker-entrypoint-initdb.d